# Generated by Django 5.2.6 on 2025-09-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=255, upload_to='uploads/media')),
                ('file_thumbnail', models.FileField(max_length=255, null=True, upload_to='uploads/media')),
                ('file_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video'), ('image', 'Image')], max_length=20)),
                ('status', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('private', 'Private'), ('pending', 'Pending'), ('deleted', 'Deleted')], max_length=20)),
                ('description', models.TextField(null=True)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('share_count', models.PositiveIntegerField(default=0)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
