# Generated by Django 5.2.6 on 2025-10-01 12:33

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='media',
            managers=[
                ('objects_active', django.db.models.manager.Manager()),
            ],
        ),
    ]
