# Generated by Django 5.2.6 on 2025-10-07 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mediahashtag',
            name='hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.hashtag'),
        ),
        migrations.AddField(
            model_name='mediahashtag',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.media'),
        ),
        migrations.AddField(
            model_name='media',
            name='hashtags',
            field=models.ManyToManyField(related_name='media_hashtags', through='media.MediaHashtag', to='media.hashtag'),
        ),
        migrations.AddConstraint(
            model_name='mediahashtag',
            constraint=models.UniqueConstraint(fields=('media', 'hashtag'), name='unique_media_hashtag'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['status'], name='idx_media_status'),
        ),
    ]
