# Generated by Django 5.2.6 on 2025-09-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file_thumbnail',
            field=models.FileField(max_length=255, null=True, upload_to='uploads/media'),
        ),
    ]
