# Generated by Django 5.2.6 on 2025-11-13 14:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='media',
            name='idx_media_status',
        ),
        migrations.AddField(
            model_name='media',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['status', 'is_approved', 'user_id'], name='idx_load_media_feed'),
        ),
    ]
