# Generated by Django 5.2.6 on 2025-11-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_remove_media_idx_media_status_media_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='unlock_price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
