# Generated by Django 5.2.6 on 2025-09-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file_type',
            field=models.CharField(choices=[('audio', 'Audio'), ('video', 'Video'), ('image', 'Image')], max_length=10, null=True),
        ),
    ]
