# Generated by Django 5.2.6 on 2025-09-15 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='status',
        ),
    ]
