# Generated by Django 5.2.6 on 2025-11-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_ready',
            field=models.BooleanField(default=True),
        ),
    ]
