# Generated by Django 5.2.6 on 2025-10-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeVerification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=20)),
                ('provider_session_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgeVerificationCountry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('country_code', models.CharField(max_length=5)),
                ('country_name', models.CharField(max_length=50)),
                ('state_code', models.CharField(blank=True, max_length=5, null=True)),
                ('state_name', models.CharField(blank=True, max_length=30, null=True)),
                ('is_age_verification_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreatorAgreement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('form_type', models.CharField(max_length=20)),
                ('form_version', models.IntegerField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
