# Generated by Django 5.2.6 on 2025-10-11 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeVerification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=20)),
                ('provider_session_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgeVerificationCountry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('country_code', models.CharField(max_length=5)),
                ('country_name', models.CharField(max_length=50)),
                ('state_code', models.CharField(blank=True, max_length=5, null=True)),
                ('state_name', models.CharField(blank=True, max_length=30, null=True)),
                ('is_age_verification_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['country_code', 'state_code', 'is_age_verification_required'], name='age_verific_country_a8d5eb_idx')],
            },
        ),
        migrations.CreateModel(
            name='CreatorAgreement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('form_type', models.CharField(max_length=20)),
                ('form_version', models.IntegerField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
