# Generated by Django 5.2.6 on 2026-01-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('age_verification', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ageverificationcountry',
            name='state_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
