# Generated by Django 5.2.6 on 2025-09-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content_id', models.IntegerField()),
                ('type', models.CharField(choices=[('user', 'User'), ('media', 'Media')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
