"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import environ

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False),
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')
APP_ENV = env('APP_ENV')
DB_TYPE = env('DB_TYPE')
DATE_TIME_FORMAT = '%m/%d/%Y %I:%M%p'

# Application definition

INSTALLED_APPS = [
    'src.authentication.apps.AuthenticationConfig',
    'src.discover.apps.DiscoverConfig',
    'src.feed.apps.FeedConfig',
    'src.inbox.apps.InboxConfig',
    'src.user.apps.UserConfig',
    'src.media.apps.MediaConfig',
    'src.core.apps.CoreConfig',
    'src.payment.apps.PaymentConfig',
    'src.engagement.apps.EngagementConfig',
    'src.follow.apps.FollowConfig',
    'src.report.apps.ReportConfig',
    'src.notification.apps.NotificationConfig',
    'src.storage.apps.StorageConfig',
    'src.age_verification.apps.AgeVerificationConfig',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_cleanup.apps.CleanupConfig',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.twitter_oauth2',

    'auditlog',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'allauth.account.middleware.AccountMiddleware',

    'auditlog.middleware.AuditlogMiddleware'
]

# Auth
SESSION_COOKIE_AGE = 86400 * 30
LOGOUT_REDIRECT_URL = '/'
LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/auth/login/'
AUTH_USER_MODEL = 'user.User'
AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app.context_processor.environment_variables',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if (DB_TYPE == 'sqlite'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
if (DB_TYPE == 'mysql'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': env('MYSQL_DATABASE'),
            'USER': env('MYSQL_USER'),
            'PASSWORD': env('MYSQL_PASSWORD'),
            'HOST': env('MYSQL_HOST'),
            'PORT': '3306',
        }
    }

# Storage
STORAGE_TYPE = env('STORAGE_TYPE')
STORAGE_CONFIG = {
    'backblaze': {
        'application_key_id': env('BACKBLAZE_APPLICATION_KEY_ID'),
        'application_key': env('BACKBLAZE_APPLICATION_KEY'),
        'bucket_name': env('BACKBLAZE_DEFAULT_BUCKET_NAME'),
    }
}
STORAGE_CDN_URL = env('STORAGE_CDN_URL')

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL = '/uploads/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = env('EMAIL_HOST')  # e.g. smtp.gmail.com, smtp.sendgrid.net, etc.
EMAIL_PORT = env('EMAIL_PORT')  # 587 for TLS, 465 for SSL, 25 (not recommended)
EMAIL_USE_TLS = env('EMAIL_USE_TLS')  # or EMAIL_USE_SSL = True
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')

DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL')
ADMIN_EMAILS = env('ADMIN_EMAILS').split(',')
SUPPORT_EMAIL = env('SUPPORT_EMAIL')

ALLOWED_HOSTS = env('ALLOWED_HOSTS').split(',')
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# allauth settings
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "optional"  # "mandatory" if you want verified emails

# Celery
CELERY_BROKER_URL = env('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND')
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TASK_ALWAYS_EAGER = False if APP_ENV == 'production' else bool(int(env('CELERY_TASK_ALWAYS_EAGER')))
CELERY_TASK_EAGER_PROPAGATES = bool(int(env('CELERY_TASK_EAGER_PROPAGATES')))

# Logging
# settings.py
import os

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,  # Keep Django’s default loggers
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'daily_file': {
            'level': 'INFO',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'when': 'midnight',  # Rotate daily at midnight
            'interval': 1,  # Every 1 day
            'backupCount': 7,  # Keep 7 days of logs
            'encoding': 'utf-8',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'app_logger': {
            'handlers': ['daily_file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}
